# Generated by Django 3.0.7 on 2021-09-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=100)),
                ('cityImage', models.CharField(max_length=100)),
            ],
        ),
    ]
