# Generated by Django 3.0.7 on 2021-09-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
