# Generated by Django 3.0.7 on 2021-09-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_delete_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechReport',
            fields=[
                ('TechReportId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeId', models.CharField(max_length=100)),
                ('EmployeeName', models.CharField(max_length=300)),
                ('techName', models.CharField(max_length=300)),
                ('techEmail', models.CharField(max_length=300)),
                ('techCompany', models.CharField(max_length=300)),
                ('techVAT', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Unread', 'Unread')], max_length=64)),
            ],
        ),
    ]
