# Generated by Django 3.0.7 on 2021-09-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0007_auto_20210928_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftReport',
            fields=[
                ('SoftReportId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeId', models.CharField(max_length=100)),
                ('softName', models.CharField(max_length=300)),
                ('softEmail', models.CharField(max_length=300)),
                ('softCompany', models.CharField(blank=True, max_length=300, null=True)),
                ('softVAT', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Unread', 'Unread')], max_length=64)),
            ],
        ),
    ]
