# Generated by Django 3.0.7 on 2021-10-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0009_employees_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='portfolio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
