# Generated by Django 3.0.7 on 2021-10-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0010_auto_20211011_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.AutoField(primary_key=True, serialize=False)),
                ('senderName', models.CharField(max_length=100)),
                ('senderEmail', models.CharField(max_length=100)),
                ('receiverName', models.CharField(max_length=100)),
                ('receiverEmail', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('sendDate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], max_length=64)),
            ],
        ),
    ]
