# Generated by Django 3.0.7 on 2021-10-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0011_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiverId',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread'), ('Archive', 'Archive')], max_length=64),
        ),
    ]
