# Generated by Django 3.0.7 on 2021-10-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0012_auto_20211011_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sendDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
