# Generated by Django 3.0.7 on 2021-10-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0013_auto_20211012_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiverId',
        ),
    ]
