# Generated by Django 3.0.7 on 2021-10-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0014_remove_message_receiverid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sendDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
