# Generated by Django 3.0.7 on 2021-11-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0003_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='small_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
