# Generated by Django 3.0.7 on 2021-12-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0004_post_small_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
