# Generated by Django 3.0.7 on 2021-12-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0006_auto_20211212_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
