# Generated by Django 3.0.7 on 2021-12-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0007_post_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='sku',
        ),
    ]
